// Coefficients / multiplicateurs communaux ICC réels par commune (2026).
// Source : tableur fourni par la courtière, compilé depuis les sources
// officielles cantonales (État de Genève ArCA-2026, VD taux 2026, VS
// coefficients + indexations 2022-2027, FR/NE tableaux 2026/2024-2026,
// JU quotités 2026). Remplace, quand la commune du client est connue et
// présente ici, le multiplicateur par défaut du chef-lieu cantonal
// (CANTON_SCALES[canton].communalMultiplierCapital dans src/lib/tax/cantons.ts).
//
// GE : couverture complète (45/45 communes), recoupée le 09.10.2026 contre
// le fichier officiel "Taux de centimes additionnels 2018-2026" (État de
// Genève) — les 42 valeurs déjà présentes concordaient exactement ; ajout
// de Bellevue, Collex-Bossy, et Genève elle-même (0.4549, cohérente avec
// communalMultiplierCapital = 0.455 déjà en place).
//
// VD : couverture quasi complète (305/~300 communes avec Cully, alias
// historique de Bourg-en-Lavaux conservé), recoupée le 09.10.2026 contre
// le fichier officiel "Arrêtés d'imposition 2026" (État de Vaud,
// www.vd.ch) — colonne "Pour-cent total" (impôt ordinaire + impôt spécial
// affecté le cas échéant, ex. Ormont-Dessous/Ormont-Dessus où les deux
// diffèrent). Les 30 valeurs déjà présentes (hors Cully/Bourg-en-Lavaux et
// La Tour-de-Peilz, où seul le total diffère du taux ordinaire affiché
// séparément dans le fichier) concordaient exactement.
//
// Unités d'origine et conversion vers le multiplicateur décimal attendu par
// computeCantonalCommunal (voir communalMult = simple * communalMult) :
//   GE centimes additionnels, VD/FR/NE coefficient en % → valeur / 100
//   JU quotité communale, VS coefficient communal (1.0-1.5) → valeur brute
//
// VS : en plus du coefficient, chaque commune a sa propre "indexation"
// (143%-176%), un second paramètre officiel (Service cantonal des
// contributions, page "Calcul du taux pour l'impôt communal") qui ajuste
// le revenu déterminant le TAUX avant application du coefficient — voir
// vsDeindexedReferenceIncome dans src/lib/tax/cantons.ts. Les 23 valeurs
// ci-dessous ont été recoupées une à une (coefficient ET indexation) avec
// le tableau officiel complet des 122 communes valaisannes (vs.ch/web/scc,
// "Coefficients_Indexations_Communes_2022-2027", colonne 2026) : les 23
// coefficients concordent exactement, confirmant aussi les indexations.
//
// JU : les 13 quotités ci-dessous ont été recoupées une à une contre le
// document officiel "Quotités d'impôt des communes et taux impôts 2026"
// (jura.ch, Service des contributions) — 12/13 concordaient exactement ;
// Le Noirmont était erroné dans la source initiale (1.30 au lieu de 1.70,
// corrigé ici avec la valeur officielle).

export interface CommunalMultiplierEntry {
  /** Multiplicateur décimal prêt à l'emploi (communalMultiplier). */
  multiplier: number;
  /** Commune fiscale 2026 réelle (après fusions) si différente de la clé. */
  fiscalCommune?: string;
  verified: "confirmed" | "provisional";
  /** VS uniquement : indexation communale réelle 2026 (%, ex. 166 pour 166%). */
  vsIndexationPercent?: number;
}

export const COMMUNAL_MULTIPLIERS: Record<string, Record<string, CommunalMultiplierEntry>> = {
  GE: {
    "Aire-la-Ville": { multiplier: 0.5, verified: "confirmed" },
    Anières: { multiplier: 0.31, verified: "confirmed" },
    Avully: { multiplier: 0.51, verified: "confirmed" },
    Avusy: { multiplier: 0.49, verified: "confirmed" },
    Bardonnex: { multiplier: 0.43, verified: "confirmed" },
    Bellevue: { multiplier: 0.39, verified: "confirmed" },
    Bernex: { multiplier: 0.48, verified: "confirmed" },
    Carouge: { multiplier: 0.4, verified: "confirmed" },
    Cartigny: { multiplier: 0.42, verified: "confirmed" },
    Chancy: { multiplier: 0.51, verified: "confirmed" },
    Choulex: { multiplier: 0.4, verified: "confirmed" },
    "Chêne-Bougeries": { multiplier: 0.32, verified: "confirmed" },
    "Chêne-Bourg": { multiplier: 0.46, verified: "confirmed" },
    "Collex-Bossy": { multiplier: 0.46, verified: "confirmed" },
    "Collonge-Bellerive": { multiplier: 0.28, verified: "confirmed" },
    Cologny: { multiplier: 0.25, verified: "confirmed" },
    Confignon: { multiplier: 0.46, verified: "confirmed" },
    Corsier: { multiplier: 0.31, verified: "confirmed" },
    Céligny: { multiplier: 0.33, verified: "confirmed" },
    Dardagny: { multiplier: 0.48, verified: "confirmed" },
    // Chef-lieu : déjà utilisé comme repli par défaut
    // (CANTON_SCALES.GE.communalMultiplierCapital = 0.455 dans cantons.ts,
    // cohérent avec ce 0.4549 officiel) — ajoutée ici explicitement pour
    // que la liste GE soit complète (45/45 communes), sans dépendre
    // implicitement du repli cantonal.
    Genève: { multiplier: 0.4549, verified: "confirmed" },
    Genthod: { multiplier: 0.25, verified: "confirmed" },
    "Grand-Saconnex": { multiplier: 0.44, verified: "confirmed" },
    Gy: { multiplier: 0.46, verified: "confirmed" },
    Hermance: { multiplier: 0.42, verified: "confirmed" },
    Jussy: { multiplier: 0.41, verified: "confirmed" },
    Laconnex: { multiplier: 0.44, verified: "confirmed" },
    Lancy: { multiplier: 0.47, verified: "confirmed" },
    Meinier: { multiplier: 0.42, verified: "confirmed" },
    Meyrin: { multiplier: 0.42, verified: "confirmed" },
    Onex: { multiplier: 0.505, verified: "confirmed" },
    "Perly-Certoux": { multiplier: 0.43, verified: "confirmed" },
    "Plan-les-Ouates": { multiplier: 0.37, verified: "confirmed" },
    "Pregny-Chambésy": { multiplier: 0.32, verified: "confirmed" },
    Presinge: { multiplier: 0.4, verified: "confirmed" },
    Puplinge: { multiplier: 0.49, verified: "confirmed" },
    Russin: { multiplier: 0.39, verified: "confirmed" },
    Satigny: { multiplier: 0.39, verified: "confirmed" },
    Soral: { multiplier: 0.44, verified: "confirmed" },
    Thônex: { multiplier: 0.44, verified: "confirmed" },
    Troinex: { multiplier: 0.4, verified: "confirmed" },
    Vandœuvres: { multiplier: 0.27, verified: "confirmed" },
    Vernier: { multiplier: 0.5, verified: "confirmed" },
    Versoix: { multiplier: 0.455, verified: "confirmed" },
    Veyrier: { multiplier: 0.37, verified: "confirmed" },
  },
  VD: {
    Aclens: { multiplier: 0.6, verified: "confirmed" },
    Agiez: { multiplier: 0.76, verified: "confirmed" },
    Aigle: { multiplier: 0.66, verified: "confirmed" },
    Allaman: { multiplier: 0.65, verified: "confirmed" },
    "Arnex-sur-Nyon": { multiplier: 0.66, verified: "confirmed" },
    "Arnex-sur-Orbe": { multiplier: 0.71, verified: "confirmed" },
    "Arzier-Le Muids": { multiplier: 0.64, verified: "confirmed" },
    Assens: { multiplier: 0.7, verified: "confirmed" },
    Aubonne: { multiplier: 0.68, verified: "confirmed" },
    Avenches: { multiplier: 0.65, verified: "confirmed" },
    Ballaigues: { multiplier: 0.65, verified: "confirmed" },
    Ballens: { multiplier: 0.73, verified: "confirmed" },
    Bassins: { multiplier: 0.725, verified: "confirmed" },
    Baulmes: { multiplier: 0.765, verified: "confirmed" },
    Bavois: { multiplier: 0.72, verified: "confirmed" },
    Begnins: { multiplier: 0.625, verified: "confirmed" },
    "Belmont-sur-Lausanne": { multiplier: 0.72, verified: "confirmed" },
    "Belmont-sur-Yverdon": { multiplier: 0.7, verified: "confirmed" },
    Bercher: { multiplier: 0.79, verified: "confirmed" },
    Berolle: { multiplier: 0.755, verified: "confirmed" },
    Bettens: { multiplier: 0.7, verified: "confirmed" },
    Bex: { multiplier: 0.71, verified: "confirmed" },
    "Bioley-Magnoux": { multiplier: 0.72, verified: "confirmed" },
    Bière: { multiplier: 0.69, verified: "confirmed" },
    "Blonay - Saint-Légier": { multiplier: 0.675, verified: "confirmed" },
    Bofflens: { multiplier: 0.69, verified: "confirmed" },
    "Bogis-Bossey": { multiplier: 0.7, verified: "confirmed" },
    Bonvillars: { multiplier: 0.67, verified: "confirmed" },
    Borex: { multiplier: 0.57, verified: "confirmed" },
    Bottens: { multiplier: 0.725, verified: "confirmed" },
    "Bougy-Villars": { multiplier: 0.62, verified: "confirmed" },
    Boulens: { multiplier: 0.715, verified: "confirmed" },
    "Bourg-en-Lavaux": { multiplier: 0.625, verified: "confirmed" },
    Bournens: { multiplier: 0.65, verified: "confirmed" },
    Boussens: { multiplier: 0.64, verified: "confirmed" },
    Bremblens: { multiplier: 0.68, verified: "confirmed" },
    "Bretigny-sur-Morrens": { multiplier: 0.76, verified: "confirmed" },
    Bretonnières: { multiplier: 0.69, verified: "confirmed" },
    Buchillon: { multiplier: 0.52, verified: "confirmed" },
    Bullet: { multiplier: 0.75, verified: "confirmed" },
    Bursinel: { multiplier: 0.62, verified: "confirmed" },
    Bursins: { multiplier: 0.71, verified: "confirmed" },
    Burtigny: { multiplier: 0.75, verified: "confirmed" },
    Bussigny: { multiplier: 0.625, verified: "confirmed" },
    "Bussy-sur-Moudon": { multiplier: 0.785, verified: "confirmed" },
    Chamblon: { multiplier: 0.66, verified: "confirmed" },
    Champagne: { multiplier: 0.65, verified: "confirmed" },
    Champtauroz: { multiplier: 0.77, verified: "confirmed" },
    Champvent: { multiplier: 0.7, verified: "confirmed" },
    Chardonne: { multiplier: 0.68, verified: "confirmed" },
    "Chavannes-de-Bogis": { multiplier: 0.58, verified: "confirmed" },
    "Chavannes-des-Bois": { multiplier: 0.66, verified: "confirmed" },
    "Chavannes-le-Chêne": { multiplier: 0.75, verified: "confirmed" },
    "Chavannes-le-Veyron": { multiplier: 0.77, verified: "confirmed" },
    "Chavannes-près-Renens": { multiplier: 0.775, verified: "confirmed" },
    "Chavannes-sur-Moudon": { multiplier: 0.7, verified: "confirmed" },
    Chavornay: { multiplier: 0.705, verified: "confirmed" },
    "Cheseaux-Noréaz": { multiplier: 0.67, verified: "confirmed" },
    "Cheseaux-sur-Lausanne": { multiplier: 0.73, verified: "confirmed" },
    Chessel: { multiplier: 0.65, verified: "confirmed" },
    Chevilly: { multiplier: 0.7, verified: "confirmed" },
    Chevroux: { multiplier: 0.685, verified: "confirmed" },
    Chexbres: { multiplier: 0.675, verified: "confirmed" },
    Chigny: { multiplier: 0.62, verified: "confirmed" },
    "Château-d'Oex": { multiplier: 0.815, verified: "confirmed" },
    Chéserex: { multiplier: 0.59, verified: "confirmed" },
    "Chêne-Pâquier": { multiplier: 0.75, verified: "confirmed" },
    Clarmont: { multiplier: 0.72, verified: "confirmed" },
    Coinsins: { multiplier: 0.49, verified: "confirmed" },
    Commugny: { multiplier: 0.58, verified: "confirmed" },
    Concise: { multiplier: 0.68, verified: "confirmed" },
    Coppet: { multiplier: 0.57, verified: "confirmed" },
    Corbeyrier: { multiplier: 0.74, verified: "confirmed" },
    "Corcelles-le-Jorat": { multiplier: 0.75, verified: "confirmed" },
    "Corcelles-près-Concise": { multiplier: 0.69, verified: "confirmed" },
    "Corcelles-près-Payerne": { multiplier: 0.65, verified: "confirmed" },
    Corseaux: { multiplier: 0.675, verified: "confirmed" },
    "Corsier-sur-Vevey": { multiplier: 0.645, verified: "confirmed" },
    Cossonay: { multiplier: 0.66, verified: "confirmed" },
    Crans: { multiplier: 0.59, verified: "confirmed" },
    Crassier: { multiplier: 0.65, verified: "confirmed" },
    Crissier: { multiplier: 0.635, verified: "confirmed" },
    Cronay: { multiplier: 0.75, verified: "confirmed" },
    Croy: { multiplier: 0.74, verified: "confirmed" },
    Cuarnens: { multiplier: 0.76, verified: "confirmed" },
    Cuarny: { multiplier: 0.73, verified: "confirmed" },
    Cudrefin: { multiplier: 0.59, verified: "confirmed" },
    Cugy: { multiplier: 0.76, verified: "confirmed" },
    Cully: { multiplier: 0.625, fiscalCommune: "Bourg-en-Lavaux", verified: "confirmed" },
    Curtilles: { multiplier: 0.71, verified: "confirmed" },
    Daillens: { multiplier: 0.66, verified: "confirmed" },
    Denens: { multiplier: 0.63, verified: "confirmed" },
    Denges: { multiplier: 0.62, verified: "confirmed" },
    Dizy: { multiplier: 0.75, verified: "confirmed" },
    Dompierre: { multiplier: 0.78, verified: "confirmed" },
    Donneloye: { multiplier: 0.73, verified: "confirmed" },
    Duillier: { multiplier: 0.66, verified: "confirmed" },
    Dully: { multiplier: 0.53, verified: "confirmed" },
    Démoret: { multiplier: 0.78, verified: "confirmed" },
    Echallens: { multiplier: 0.725, verified: "confirmed" },
    Echandens: { multiplier: 0.605, verified: "confirmed" },
    Echichens: { multiplier: 0.66, verified: "confirmed" },
    Eclépens: { multiplier: 0.46, verified: "confirmed" },
    Ecublens: { multiplier: 0.625, verified: "confirmed" },
    Epalinges: { multiplier: 0.645, verified: "confirmed" },
    Ependes: { multiplier: 0.735, verified: "confirmed" },
    "Essertines-sur-Rolle": { multiplier: 0.665, verified: "confirmed" },
    "Essertines-sur-Yverdon": { multiplier: 0.72, verified: "confirmed" },
    Etagnières: { multiplier: 0.73, verified: "confirmed" },
    Etoy: { multiplier: 0.6, verified: "confirmed" },
    Eysins: { multiplier: 0.595, verified: "confirmed" },
    Faoug: { multiplier: 0.65, verified: "confirmed" },
    Ferreyres: { multiplier: 0.76, verified: "confirmed" },
    Fey: { multiplier: 0.75, verified: "confirmed" },
    Fiez: { multiplier: 0.69, verified: "confirmed" },
    "Fontaines-sur-Grandson": { multiplier: 0.72, verified: "confirmed" },
    "Forel (Lavaux)": { multiplier: 0.69, verified: "confirmed" },
    Founex: { multiplier: 0.57, verified: "confirmed" },
    Froideville: { multiplier: 0.72, verified: "confirmed" },
    Féchy: { multiplier: 0.64, verified: "confirmed" },
    Genolier: { multiplier: 0.52, verified: "confirmed" },
    Giez: { multiplier: 0.69, verified: "confirmed" },
    Gilly: { multiplier: 0.625, verified: "confirmed" },
    Gimel: { multiplier: 0.73, verified: "confirmed" },
    Gingins: { multiplier: 0.6, verified: "confirmed" },
    Givrins: { multiplier: 0.685, verified: "confirmed" },
    Gland: { multiplier: 0.61, verified: "confirmed" },
    Gollion: { multiplier: 0.74, verified: "confirmed" },
    Goumoëns: { multiplier: 0.755, verified: "confirmed" },
    Grancy: { multiplier: 0.7, verified: "confirmed" },
    Grandcour: { multiplier: 0.72, verified: "confirmed" },
    Grandevent: { multiplier: 0.71, verified: "confirmed" },
    Grandson: { multiplier: 0.69, verified: "confirmed" },
    Grens: { multiplier: 0.6, verified: "confirmed" },
    Gryon: { multiplier: 0.735, verified: "confirmed" },
    Hautemorges: { multiplier: 0.68, verified: "confirmed" },
    Henniez: { multiplier: 0.69, verified: "confirmed" },
    Hermenches: { multiplier: 0.78, verified: "confirmed" },
    Jongny: { multiplier: 0.695, verified: "confirmed" },
    "Jorat-Menthue": { multiplier: 0.705, verified: "confirmed" },
    "Jorat-Mézières": { multiplier: 0.71, verified: "confirmed" },
    "Jouxtens-Mézery": { multiplier: 0.59, verified: "confirmed" },
    Juriens: { multiplier: 0.79, verified: "confirmed" },
    "L'Abbaye": { multiplier: 0.76, verified: "confirmed" },
    "L'Abergement": { multiplier: 0.8, verified: "confirmed" },
    "L'Isle": { multiplier: 0.75, verified: "confirmed" },
    "L'Orient (fraction)": { multiplier: 0.1, verified: "confirmed" },
    "La Chaux (Cossonay)": { multiplier: 0.76, verified: "confirmed" },
    "La Praz": { multiplier: 0.83, verified: "confirmed" },
    "La Rippe": { multiplier: 0.635, verified: "confirmed" },
    "La Sarraz": { multiplier: 0.7, verified: "confirmed" },
    "La Tour-de-Peilz": { multiplier: 0.64, verified: "confirmed" },
    Lausanne: { multiplier: 0.785, verified: "confirmed" },
    "Lavey-Morcles": { multiplier: 0.715, verified: "confirmed" },
    Lavigny: { multiplier: 0.73, verified: "confirmed" },
    "Le Brassus (fraction)": { multiplier: 0.08, verified: "confirmed" },
    "Le Chenit": { multiplier: 0.585, verified: "confirmed" },
    "Le Lieu": { multiplier: 0.7, verified: "confirmed" },
    "Le Mont-sur-Lausanne": { multiplier: 0.72, verified: "confirmed" },
    "Le Sentier (fraction)": { multiplier: 0.08, verified: "confirmed" },
    "Le Vaud": { multiplier: 0.69, verified: "confirmed" },
    "Les Bioux (fraction)": { multiplier: 0.03, verified: "confirmed" },
    "Les Clées": { multiplier: 0.8, verified: "confirmed" },
    Leysin: { multiplier: 0.78, verified: "confirmed" },
    Lignerolle: { multiplier: 0.785, verified: "confirmed" },
    Lonay: { multiplier: 0.55, verified: "confirmed" },
    Longirod: { multiplier: 0.775, verified: "confirmed" },
    Lovatens: { multiplier: 0.75, verified: "confirmed" },
    Lucens: { multiplier: 0.695, verified: "confirmed" },
    Luins: { multiplier: 0.585, verified: "confirmed" },
    Lully: { multiplier: 0.58, verified: "confirmed" },
    "Lussery-Villars": { multiplier: 0.75, verified: "confirmed" },
    "Lussy-sur-Morges": { multiplier: 0.615, verified: "confirmed" },
    Lutry: { multiplier: 0.54, verified: "confirmed" },
    Maracon: { multiplier: 0.745, verified: "confirmed" },
    Marchissy: { multiplier: 0.775, verified: "confirmed" },
    Mathod: { multiplier: 0.72, verified: "confirmed" },
    Mauborget: { multiplier: 0.7, verified: "confirmed" },
    Mauraz: { multiplier: 0.75, verified: "confirmed" },
    Mex: { multiplier: 0.595, verified: "confirmed" },
    Mies: { multiplier: 0.54, verified: "confirmed" },
    Missy: { multiplier: 0.69, verified: "confirmed" },
    Moiry: { multiplier: 0.76, verified: "confirmed" },
    Mollens: { multiplier: 0.74, verified: "confirmed" },
    Molondin: { multiplier: 0.81, verified: "confirmed" },
    "Mont-la-Ville": { multiplier: 0.76, verified: "confirmed" },
    "Mont-sur-Rolle": { multiplier: 0.62, verified: "confirmed" },
    "Montagny-près-Yverdon": { multiplier: 0.645, verified: "confirmed" },
    Montanaire: { multiplier: 0.7, verified: "confirmed" },
    Montcherand: { multiplier: 0.72, verified: "confirmed" },
    Montilliez: { multiplier: 0.725, verified: "confirmed" },
    Montpreveyres: { multiplier: 0.745, verified: "confirmed" },
    Montreux: { multiplier: 0.65, verified: "confirmed" },
    Montricher: { multiplier: 0.64, verified: "confirmed" },
    Morges: { multiplier: 0.67, verified: "confirmed" },
    Morrens: { multiplier: 0.74, verified: "confirmed" },
    Moudon: { multiplier: 0.725, verified: "confirmed" },
    Mutrux: { multiplier: 0.8, verified: "confirmed" },
    Novalles: { multiplier: 0.76, verified: "confirmed" },
    Noville: { multiplier: 0.75, verified: "confirmed" },
    Nyon: { multiplier: 0.61, verified: "confirmed" },
    Ogens: { multiplier: 0.76, verified: "confirmed" },
    Ollon: { multiplier: 0.68, verified: "confirmed" },
    Onnens: { multiplier: 0.65, verified: "confirmed" },
    Oppens: { multiplier: 0.79, verified: "confirmed" },
    Orbe: { multiplier: 0.755, verified: "confirmed" },
    Orges: { multiplier: 0.74, verified: "confirmed" },
    "Ormont-Dessous": { multiplier: 0.77, verified: "confirmed" },
    "Ormont-Dessus": { multiplier: 0.76, verified: "confirmed" },
    Orny: { multiplier: 0.73, verified: "confirmed" },
    Oron: { multiplier: 0.69, verified: "confirmed" },
    Orzens: { multiplier: 0.79, verified: "confirmed" },
    "Oulens-sous-Echallens": { multiplier: 0.71, verified: "confirmed" },
    Pailly: { multiplier: 0.76, verified: "confirmed" },
    Paudex: { multiplier: 0.665, verified: "confirmed" },
    Payerne: { multiplier: 0.7, verified: "confirmed" },
    Penthalaz: { multiplier: 0.725, verified: "confirmed" },
    Penthaz: { multiplier: 0.695, verified: "confirmed" },
    Penthéréaz: { multiplier: 0.74, verified: "confirmed" },
    Perroy: { multiplier: 0.605, verified: "confirmed" },
    "Poliez-Pittet": { multiplier: 0.73, verified: "confirmed" },
    Pompaples: { multiplier: 0.66, verified: "confirmed" },
    Pomy: { multiplier: 0.71, verified: "confirmed" },
    Prangins: { multiplier: 0.57, verified: "confirmed" },
    Premier: { multiplier: 0.795, verified: "confirmed" },
    Prilly: { multiplier: 0.725, verified: "confirmed" },
    Provence: { multiplier: 0.81, verified: "confirmed" },
    Préverenges: { multiplier: 0.65, verified: "confirmed" },
    Prévonloup: { multiplier: 0.725, verified: "confirmed" },
    Puidoux: { multiplier: 0.685, verified: "confirmed" },
    Pully: { multiplier: 0.61, verified: "confirmed" },
    Rances: { multiplier: 0.765, verified: "confirmed" },
    Renens: { multiplier: 0.77, verified: "confirmed" },
    Rennaz: { multiplier: 0.64, verified: "confirmed" },
    Rivaz: { multiplier: 0.62, verified: "confirmed" },
    Roche: { multiplier: 0.665, verified: "confirmed" },
    Rolle: { multiplier: 0.595, verified: "confirmed" },
    "Romainmôtier-Envy": { multiplier: 0.81, verified: "confirmed" },
    "Romanel-sur-Lausanne": { multiplier: 0.705, verified: "confirmed" },
    "Romanel-sur-Morges": { multiplier: 0.56, verified: "confirmed" },
    Ropraz: { multiplier: 0.775, verified: "confirmed" },
    Rossenges: { multiplier: 0.65, verified: "confirmed" },
    Rossinière: { multiplier: 0.81, verified: "confirmed" },
    Rougemont: { multiplier: 0.79, verified: "confirmed" },
    Rovray: { multiplier: 0.73, verified: "confirmed" },
    Rueyres: { multiplier: 0.73, verified: "confirmed" },
    "Saint-Barthélemy": { multiplier: 0.77, verified: "confirmed" },
    "Saint-Cergue": { multiplier: 0.66, verified: "confirmed" },
    "Saint-George": { multiplier: 0.695, verified: "confirmed" },
    "Saint-Livres": { multiplier: 0.69, verified: "confirmed" },
    "Saint-Oyens": { multiplier: 0.77, verified: "confirmed" },
    "Saint-Prex": { multiplier: 0.59, verified: "confirmed" },
    "Saint-Sulpice": { multiplier: 0.55, verified: "confirmed" },
    "Sainte-Croix": { multiplier: 0.7, verified: "confirmed" },
    Saubraz: { multiplier: 0.77, verified: "confirmed" },
    Savigny: { multiplier: 0.69, verified: "confirmed" },
    Senarclens: { multiplier: 0.685, verified: "confirmed" },
    Sergey: { multiplier: 0.76, verified: "confirmed" },
    Servion: { multiplier: 0.69, verified: "confirmed" },
    "Signy-Avenex": { multiplier: 0.58, verified: "confirmed" },
    "St-Saphorin (Lavaux)": { multiplier: 0.74, verified: "confirmed" },
    Suchy: { multiplier: 0.7, verified: "confirmed" },
    Sullens: { multiplier: 0.64, verified: "confirmed" },
    Suscévaz: { multiplier: 0.72, verified: "confirmed" },
    Syens: { multiplier: 0.65, verified: "confirmed" },
    Tannay: { multiplier: 0.605, verified: "confirmed" },
    Tartegnin: { multiplier: 0.79, verified: "confirmed" },
    Tolochenaz: { multiplier: 0.64, verified: "confirmed" },
    Trey: { multiplier: 0.78, verified: "confirmed" },
    Treycovagnes: { multiplier: 0.73, verified: "confirmed" },
    Treytorrens: { multiplier: 0.815, verified: "confirmed" },
    Trélex: { multiplier: 0.57, verified: "confirmed" },
    Tévenon: { multiplier: 0.715, verified: "confirmed" },
    Ursins: { multiplier: 0.75, verified: "confirmed" },
    Valbroye: { multiplier: 0.705, verified: "confirmed" },
    "Valeyres-sous-Montagny": { multiplier: 0.705, verified: "confirmed" },
    "Valeyres-sous-Rances": { multiplier: 0.71, verified: "confirmed" },
    "Valeyres-sous-Ursins": { multiplier: 0.77, verified: "confirmed" },
    Vallorbe: { multiplier: 0.7, verified: "confirmed" },
    Vaulion: { multiplier: 0.81, verified: "confirmed" },
    "Vaux-sur-Morges": { multiplier: 0.56, verified: "confirmed" },
    Vevey: { multiplier: 0.745, verified: "confirmed" },
    Veytaux: { multiplier: 0.65, verified: "confirmed" },
    Vich: { multiplier: 0.63, verified: "confirmed" },
    "Villars-Epeney": { multiplier: 0.72, verified: "confirmed" },
    "Villars-Sainte-Croix": { multiplier: 0.605, verified: "confirmed" },
    "Villars-le-Comte": { multiplier: 0.68, verified: "confirmed" },
    "Villars-le-Terroir": { multiplier: 0.76, verified: "confirmed" },
    "Villars-sous-Yens": { multiplier: 0.74, verified: "confirmed" },
    Villarzel: { multiplier: 0.75, verified: "confirmed" },
    Villeneuve: { multiplier: 0.665, verified: "confirmed" },
    Vinzel: { multiplier: 0.65, verified: "confirmed" },
    Vuarrens: { multiplier: 0.735, verified: "confirmed" },
    Vucherens: { multiplier: 0.75, verified: "confirmed" },
    "Vufflens-la-Ville": { multiplier: 0.65, verified: "confirmed" },
    "Vufflens-le-Château": { multiplier: 0.605, verified: "confirmed" },
    "Vugelles-La Mothe": { multiplier: 0.7, verified: "confirmed" },
    Vuiteboeuf: { multiplier: 0.75, verified: "confirmed" },
    Vulliens: { multiplier: 0.74, verified: "confirmed" },
    Vullierens: { multiplier: 0.76, verified: "confirmed" },
    "Vully-les-Lacs": { multiplier: 0.67, verified: "confirmed" },
    Yens: { multiplier: 0.68, verified: "confirmed" },
    "Yverdon-les-Bains": { multiplier: 0.75, verified: "confirmed" },
    Yvonand: { multiplier: 0.73, verified: "confirmed" },
    Yvorne: { multiplier: 0.715, verified: "confirmed" },
  },
  VS: {
    Ardon: { multiplier: 1.3, verified: "confirmed", vsIndexationPercent: 166 },
    Bagnes: {
      multiplier: 1,
      fiscalCommune: "Val de Bagnes",
      verified: "confirmed",
      vsIndexationPercent: 176,
    },
    "Brigue-Glis": {
      multiplier: 1,
      fiscalCommune: "Brig/Glis",
      verified: "confirmed",
      vsIndexationPercent: 176,
    },
    Chamoson: { multiplier: 1.25, verified: "confirmed", vsIndexationPercent: 143 },
    Conthey: { multiplier: 1.2, verified: "confirmed", vsIndexationPercent: 163 },
    "Crans-Montana": { multiplier: 1.15, verified: "confirmed", vsIndexationPercent: 176 },
    Fully: { multiplier: 1.2, verified: "confirmed", vsIndexationPercent: 165 },
    Grimisuat: { multiplier: 1.25, verified: "confirmed", vsIndexationPercent: 163 },
    Hérémence: { multiplier: 1, verified: "confirmed", vsIndexationPercent: 176 },
    Martigny: { multiplier: 1.1, verified: "confirmed", vsIndexationPercent: 166 },
    Monthey: { multiplier: 1.2, verified: "confirmed", vsIndexationPercent: 170 },
    Naters: { multiplier: 1.1, verified: "confirmed", vsIndexationPercent: 176 },
    Nendaz: { multiplier: 1.3, verified: "confirmed", vsIndexationPercent: 156 },
    Riddes: { multiplier: 1.25, verified: "confirmed", vsIndexationPercent: 153 },
    "Saint-Maurice": { multiplier: 1.25, verified: "confirmed", vsIndexationPercent: 163 },
    Savièse: { multiplier: 1.15, verified: "confirmed", vsIndexationPercent: 156 },
    Saxon: { multiplier: 1.2, verified: "confirmed", vsIndexationPercent: 166 },
    Sierre: { multiplier: 1.2, verified: "confirmed", vsIndexationPercent: 161 },
    // Chef-lieu cantonal : coefficient déjà utilisé comme repli par défaut
    // (CANTON_SCALES.VS.communalMultiplierCapital dans cantons.ts), mais
    // l'indexation manquait ici — le moteur sautait entièrement la
    // dé-indexation pour Sion (voir cantons.ts VS_CANTONAL_INDEXATION_
    // PERCENT_2026 pour le même problème côté cantonal). Indexation 176%
    // calibrée par recherche numérique contre un cas réel AFC
    // (swisstaxcalculator.estv.admin.ch, Sion, personne seule, 0 enfant,
    // 80'000 CHF brut) : reproduit 4'342.15 CHF contre 4'342 CHF réels
    // (écart 0.15 CHF) — voir cantons.test.ts.
    Sion: { multiplier: 1.1, verified: "confirmed", vsIndexationPercent: 176 },
    Verbier: {
      multiplier: 1,
      fiscalCommune: "Val de Bagnes",
      verified: "confirmed",
      vsIndexationPercent: 176,
    },
    Viège: {
      multiplier: 1.1,
      fiscalCommune: "Visp",
      verified: "confirmed",
      vsIndexationPercent: 176,
    },
    Vouvry: { multiplier: 1.25, verified: "confirmed", vsIndexationPercent: 158 },
    Vétroz: { multiplier: 1.15, verified: "confirmed", vsIndexationPercent: 163 },
    Zermatt: { multiplier: 1, verified: "confirmed", vsIndexationPercent: 176 },
  },
  FR: {
    Belfaux: { multiplier: 0.84, verified: "confirmed" },
    Bulle: { multiplier: 0.743, verified: "confirmed" },
    "Châtel-Saint-Denis": { multiplier: 0.836, verified: "confirmed" },
    Düdingen: { multiplier: 0.82, verified: "confirmed" },
    Estavayer: { multiplier: 0.84, verified: "confirmed" },
    Givisiez: { multiplier: 0.7, verified: "confirmed" },
    "Granges-Paccot": { multiplier: 0.678, verified: "confirmed" },
    Gruyères: { multiplier: 0.8, verified: "confirmed" },
    Guin: { multiplier: 0.82, verified: "confirmed" },
    Kerzers: { multiplier: 0.79, verified: "confirmed" },
    "Le Mouret": { multiplier: 0.845, verified: "confirmed" },
    Marly: { multiplier: 0.89, verified: "confirmed" },
    Murten: { multiplier: 0.62, verified: "confirmed" },
    Romont: { multiplier: 0.9, verified: "confirmed" },
    Tafers: { multiplier: 0.75, verified: "confirmed" },
    "Villars-sur-Glâne": { multiplier: 0.639, verified: "confirmed" },
  },
  NE: {
    Boudry: { multiplier: 0.68, verified: "confirmed" },
    Cernier: { multiplier: 0.66, fiscalCommune: "Val-de-Ruz", verified: "confirmed" },
    Colombier: { multiplier: 0.63, fiscalCommune: "Milvignes", verified: "confirmed" },
    Cortaillod: { multiplier: 0.66, verified: "confirmed" },
    Couvet: { multiplier: 0.76, fiscalCommune: "Val-de-Travers", verified: "confirmed" },
    Fleurier: { multiplier: 0.76, fiscalCommune: "Val-de-Travers", verified: "confirmed" },
    Hauterive: { multiplier: 0.68, fiscalCommune: "Laténa", verified: "confirmed" },
    "La Chaux-de-Fonds": { multiplier: 0.75, verified: "confirmed" },
    "Le Locle": { multiplier: 0.69, verified: "confirmed" },
    "Marin-Epagnier": { multiplier: 0.68, fiscalCommune: "Laténa", verified: "confirmed" },
    Peseux: { multiplier: 0.65, fiscalCommune: "Neuchâtel", verified: "confirmed" },
    "Saint-Blaise": { multiplier: 0.68, fiscalCommune: "Laténa", verified: "confirmed" },
    "Val-de-Ruz": { multiplier: 0.66, verified: "confirmed" },
    "Val-de-Travers": { multiplier: 0.76, verified: "confirmed" },
  },
  JU: {
    Alle: { multiplier: 2.25, verified: "confirmed" },
    Bassecourt: { multiplier: 2.1, fiscalCommune: "Haute-Sorne", verified: "confirmed" },
    Boncourt: { multiplier: 1.55, verified: "confirmed" },
    Courrendlin: { multiplier: 2.25, verified: "confirmed" },
    Courroux: { multiplier: 2.15, verified: "confirmed" },
    Courtételle: { multiplier: 1.65, verified: "confirmed" },
    Develier: { multiplier: 1.95, verified: "confirmed" },
    // Corrigé : 1.70 (document officiel 2026), la source initiale donnait
    // 1.30 par erreur.
    "Le Noirmont": { multiplier: 1.7, verified: "confirmed" },
    "Les Breuleux": { multiplier: 1.3, verified: "confirmed" },
    Movelier: { multiplier: 2.25, verified: "confirmed" },
    Porrentruy: { multiplier: 2.05, verified: "confirmed" },
    Saignelégier: { multiplier: 2.3, verified: "confirmed" },
    Vicques: { multiplier: 2.2, fiscalCommune: "Val Terbi", verified: "confirmed" },
  },
};

/**
 * Multiplicateur communal réel pour une commune donnée, si connue.
 * undefined si canton/commune absent de la liste → l'appelant garde le
 * comportement existant (chef-lieu par défaut via communalMultiplierCapital).
 */
export function getCommunalMultiplier(
  canton: string | null | undefined,
  commune: string | null | undefined,
): number | undefined {
  if (!canton || !commune) return undefined;
  const entry = COMMUNAL_MULTIPLIERS[canton.toUpperCase()]?.[commune.trim()];
  return entry?.multiplier;
}

/**
 * VS uniquement : indexation communale réelle pour une commune donnée, si
 * connue. undefined pour tout autre canton, ou si la commune est absente de
 * la liste → l'appelant garde le comportement existant (taux lu directement
 * sur le revenu réel, sans dé-indexation).
 */
export function getVsIndexation(
  canton: string | null | undefined,
  commune: string | null | undefined,
): number | undefined {
  if (!canton || canton.toUpperCase() !== "VS" || !commune) return undefined;
  const entry = COMMUNAL_MULTIPLIERS.VS?.[commune.trim()];
  return entry?.vsIndexationPercent;
}
