// Coefficients / multiplicateurs communaux ICC réels par commune (2026).
// Source : tableur fourni par la courtière, compilé depuis les sources
// officielles cantonales (État de Genève ArCA-2026, VD taux 2026, VS
// coefficients + indexations 2022-2027, FR/NE tableaux 2026/2024-2026,
// JU quotités 2026). Remplace, quand la commune du client est connue et
// présente ici, le multiplicateur par défaut du chef-lieu cantonal
// (CANTON_SCALES[canton].communalMultiplierCapital dans src/lib/tax/cantons.ts).
//
// GE : couverture complète (45/45 communes), recoupée le 09.10.2026 contre
// le fichier officiel "Taux de centimes additionnels 2018-2026" (État de
// Genève) — les 42 valeurs déjà présentes concordaient exactement ; ajout
// de Bellevue, Collex-Bossy, et Genève elle-même (0.4549, cohérente avec
// communalMultiplierCapital = 0.455 déjà en place).
//
// VD : couverture quasi complète (305/~300 communes avec Cully, alias
// historique de Bourg-en-Lavaux conservé), recoupée le 09.10.2026 contre
// le fichier officiel "Arrêtés d'imposition 2026" (État de Vaud,
// www.vd.ch) — colonne "Pour-cent total" (impôt ordinaire + impôt spécial
// affecté le cas échéant, ex. Ormont-Dessous/Ormont-Dessus où les deux
// diffèrent). Les 30 valeurs déjà présentes (hors Cully/Bourg-en-Lavaux et
// La Tour-de-Peilz, où seul le total diffère du taux ordinaire affiché
// séparément dans le fichier) concordaient exactement.
//
// FR : couverture complète (120 communes, 119 du fichier officiel + Guin
// ajouté en alias bilingue de Düdingen), recoupée le 09.10.2026 contre le
// fichier officiel "Coefficients et taux d'impôts" (État de Fribourg) —
// colonne "Impôt sur le revenu et la fortune, en % de l'impôt cantonal de
// base". Les 16 valeurs déjà présentes concordaient exactement (une fois
// le suffixe "(FR)" de désambiguïsation inter-cantonale retiré, ex.
// "Romont (FR)" → "Romont", déjà stocké sans suffixe).
//
// NE : couverture complète (34 communes, les 14 déjà présentes
// concordaient exactement), recoupée le 09.10.2026 contre la page
// officielle "Coefficients communaux et cantonal en vigueur dans les
// communes neuchâteloises" (ne.ch), colonne 2026. Confirme aussi la
// quotité cantonale (124%) et le coefficient du chef-lieu Neuchâtel
// (65%), déjà corrects dans CANTON_SCALES.NE (cantons.ts).
//
// JU : couverture complète (53 communes, dont Moutier qui a rejoint le
// canton du Jura au 01.01.2026), recoupée le 09.10.2026 contre le
// document officiel "Quotités d'impôt des communes et taux impôts 2026"
// (Service des contributions, jura.ch), un district par page. Les 13
// valeurs déjà présentes concordaient exactement. Les sous-entrées du
// document identifiant d'anciens villages fusionnés (ex. "Haute-Sorne
// (Courf.)", "Val Terbi (Vermes)", "Basse-Allaine (Buix)") partagent
// toutes le même multiplicateur que leur commune civile de rattachement
// (seul le taux de l'impôt ecclésiastique, non utilisé ici, diffère) —
// elles ne sont donc pas dupliquées comme alias distincts, hors
// Bassecourt et Vicques déjà présents. Confirme aussi la quotité
// cantonale (285%) et le coefficient du chef-lieu Delémont (190%), déjà
// corrects dans CANTON_SCALES.JU (cantons.ts).
//
// VS : couverture complète (122/122 communes + 4 alias historiques/
// bilingues), recoupée le 09.10.2026 contre le document officiel
// "Coefficients et indexations des communes valaisannes 2022-2027"
// (Service cantonal des contributions, colonne 2026) — seul document qui
// fournit à la fois le coefficient communal ET l'indexation par commune,
// les deux valeurs nécessaires au calcul VS. 23 des 24 valeurs déjà
// présentes concordaient exactement (dont Sion, confirmant à 176% la
// calibration numérique précédente). Une erreur trouvée et corrigée :
// Viège/Visp avait vsIndexationPercent 176 (valeur par défaut non
// sourcée) au lieu de 166 (valeur officielle 2026). Noms des communes
// fusionnées repris sous leur forme officielle actuelle (ex. "Val de
// Bagnes", "Goms", "Crans-Montana") sans dupliquer les anciens villages
// listés entre parenthèses dans le document, même logique que JU/FR.
// Alias conservés : Bagnes et Verbier → Val de Bagnes, Brigue-Glis →
// Brig/Glis, Viège → Visp (noms français d'usage pour des communes au
// nom officiel germanophone/fusionné).
//
// Unités d'origine et conversion vers le multiplicateur décimal attendu par
// computeCantonalCommunal (voir communalMult = simple * communalMult) :
//   GE centimes additionnels, VD/FR/NE coefficient en % → valeur / 100
//   JU quotité communale, VS coefficient communal (1.0-1.5) → valeur brute
//
// VS : en plus du coefficient, chaque commune a sa propre "indexation"
// (143%-176%), un second paramètre officiel (Service cantonal des
// contributions, page "Calcul du taux pour l'impôt communal") qui ajuste
// le revenu déterminant le TAUX avant application du coefficient — voir
// vsDeindexedReferenceIncome dans src/lib/tax/cantons.ts. Les 23 valeurs
// ci-dessous ont été recoupées une à une (coefficient ET indexation) avec
// le tableau officiel complet des 122 communes valaisannes (vs.ch/web/scc,
// "Coefficients_Indexations_Communes_2022-2027", colonne 2026) : les 23
// coefficients concordent exactement, confirmant aussi les indexations.
//
// JU : les 13 quotités ci-dessous ont été recoupées une à une contre le
// document officiel "Quotités d'impôt des communes et taux impôts 2026"
// (jura.ch, Service des contributions) — 12/13 concordaient exactement ;
// Le Noirmont était erroné dans la source initiale (1.30 au lieu de 1.70,
// corrigé ici avec la valeur officielle).

export interface CommunalMultiplierEntry {
  /** Multiplicateur décimal prêt à l'emploi (communalMultiplier). */
  multiplier: number;
  /** Commune fiscale 2026 réelle (après fusions) si différente de la clé. */
  fiscalCommune?: string;
  verified: "confirmed" | "provisional";
  /** VS uniquement : indexation communale réelle 2026 (%, ex. 166 pour 166%). */
  vsIndexationPercent?: number;
}

export const COMMUNAL_MULTIPLIERS: Record<string, Record<string, CommunalMultiplierEntry>> = {
  GE: {
    "Aire-la-Ville": { multiplier: 0.5, verified: "confirmed" },
    Anières: { multiplier: 0.31, verified: "confirmed" },
    Avully: { multiplier: 0.51, verified: "confirmed" },
    Avusy: { multiplier: 0.49, verified: "confirmed" },
    Bardonnex: { multiplier: 0.43, verified: "confirmed" },
    Bellevue: { multiplier: 0.39, verified: "confirmed" },
    Bernex: { multiplier: 0.48, verified: "confirmed" },
    Carouge: { multiplier: 0.4, verified: "confirmed" },
    Cartigny: { multiplier: 0.42, verified: "confirmed" },
    Chancy: { multiplier: 0.51, verified: "confirmed" },
    Choulex: { multiplier: 0.4, verified: "confirmed" },
    "Chêne-Bougeries": { multiplier: 0.32, verified: "confirmed" },
    "Chêne-Bourg": { multiplier: 0.46, verified: "confirmed" },
    "Collex-Bossy": { multiplier: 0.46, verified: "confirmed" },
    "Collonge-Bellerive": { multiplier: 0.28, verified: "confirmed" },
    Cologny: { multiplier: 0.25, verified: "confirmed" },
    Confignon: { multiplier: 0.46, verified: "confirmed" },
    Corsier: { multiplier: 0.31, verified: "confirmed" },
    Céligny: { multiplier: 0.33, verified: "confirmed" },
    Dardagny: { multiplier: 0.48, verified: "confirmed" },
    // Chef-lieu : déjà utilisé comme repli par défaut
    // (CANTON_SCALES.GE.communalMultiplierCapital = 0.455 dans cantons.ts,
    // cohérent avec ce 0.4549 officiel) — ajoutée ici explicitement pour
    // que la liste GE soit complète (45/45 communes), sans dépendre
    // implicitement du repli cantonal.
    Genève: { multiplier: 0.4549, verified: "confirmed" },
    Genthod: { multiplier: 0.25, verified: "confirmed" },
    "Grand-Saconnex": { multiplier: 0.44, verified: "confirmed" },
    Gy: { multiplier: 0.46, verified: "confirmed" },
    Hermance: { multiplier: 0.42, verified: "confirmed" },
    Jussy: { multiplier: 0.41, verified: "confirmed" },
    Laconnex: { multiplier: 0.44, verified: "confirmed" },
    Lancy: { multiplier: 0.47, verified: "confirmed" },
    Meinier: { multiplier: 0.42, verified: "confirmed" },
    Meyrin: { multiplier: 0.42, verified: "confirmed" },
    Onex: { multiplier: 0.505, verified: "confirmed" },
    "Perly-Certoux": { multiplier: 0.43, verified: "confirmed" },
    "Plan-les-Ouates": { multiplier: 0.37, verified: "confirmed" },
    "Pregny-Chambésy": { multiplier: 0.32, verified: "confirmed" },
    Presinge: { multiplier: 0.4, verified: "confirmed" },
    Puplinge: { multiplier: 0.49, verified: "confirmed" },
    Russin: { multiplier: 0.39, verified: "confirmed" },
    Satigny: { multiplier: 0.39, verified: "confirmed" },
    Soral: { multiplier: 0.44, verified: "confirmed" },
    Thônex: { multiplier: 0.44, verified: "confirmed" },
    Troinex: { multiplier: 0.4, verified: "confirmed" },
    Vandœuvres: { multiplier: 0.27, verified: "confirmed" },
    Vernier: { multiplier: 0.5, verified: "confirmed" },
    Versoix: { multiplier: 0.455, verified: "confirmed" },
    Veyrier: { multiplier: 0.37, verified: "confirmed" },
  },
  VD: {
    Aclens: { multiplier: 0.6, verified: "confirmed" },
    Agiez: { multiplier: 0.76, verified: "confirmed" },
    Aigle: { multiplier: 0.66, verified: "confirmed" },
    Allaman: { multiplier: 0.65, verified: "confirmed" },
    "Arnex-sur-Nyon": { multiplier: 0.66, verified: "confirmed" },
    "Arnex-sur-Orbe": { multiplier: 0.71, verified: "confirmed" },
    "Arzier-Le Muids": { multiplier: 0.64, verified: "confirmed" },
    Assens: { multiplier: 0.7, verified: "confirmed" },
    Aubonne: { multiplier: 0.68, verified: "confirmed" },
    Avenches: { multiplier: 0.65, verified: "confirmed" },
    Ballaigues: { multiplier: 0.65, verified: "confirmed" },
    Ballens: { multiplier: 0.73, verified: "confirmed" },
    Bassins: { multiplier: 0.725, verified: "confirmed" },
    Baulmes: { multiplier: 0.765, verified: "confirmed" },
    Bavois: { multiplier: 0.72, verified: "confirmed" },
    Begnins: { multiplier: 0.625, verified: "confirmed" },
    "Belmont-sur-Lausanne": { multiplier: 0.72, verified: "confirmed" },
    "Belmont-sur-Yverdon": { multiplier: 0.7, verified: "confirmed" },
    Bercher: { multiplier: 0.79, verified: "confirmed" },
    Berolle: { multiplier: 0.755, verified: "confirmed" },
    Bettens: { multiplier: 0.7, verified: "confirmed" },
    Bex: { multiplier: 0.71, verified: "confirmed" },
    "Bioley-Magnoux": { multiplier: 0.72, verified: "confirmed" },
    Bière: { multiplier: 0.69, verified: "confirmed" },
    "Blonay - Saint-Légier": { multiplier: 0.675, verified: "confirmed" },
    Bofflens: { multiplier: 0.69, verified: "confirmed" },
    "Bogis-Bossey": { multiplier: 0.7, verified: "confirmed" },
    Bonvillars: { multiplier: 0.67, verified: "confirmed" },
    Borex: { multiplier: 0.57, verified: "confirmed" },
    Bottens: { multiplier: 0.725, verified: "confirmed" },
    "Bougy-Villars": { multiplier: 0.62, verified: "confirmed" },
    Boulens: { multiplier: 0.715, verified: "confirmed" },
    "Bourg-en-Lavaux": { multiplier: 0.625, verified: "confirmed" },
    Bournens: { multiplier: 0.65, verified: "confirmed" },
    Boussens: { multiplier: 0.64, verified: "confirmed" },
    Bremblens: { multiplier: 0.68, verified: "confirmed" },
    "Bretigny-sur-Morrens": { multiplier: 0.76, verified: "confirmed" },
    Bretonnières: { multiplier: 0.69, verified: "confirmed" },
    Buchillon: { multiplier: 0.52, verified: "confirmed" },
    Bullet: { multiplier: 0.75, verified: "confirmed" },
    Bursinel: { multiplier: 0.62, verified: "confirmed" },
    Bursins: { multiplier: 0.71, verified: "confirmed" },
    Burtigny: { multiplier: 0.75, verified: "confirmed" },
    Bussigny: { multiplier: 0.625, verified: "confirmed" },
    "Bussy-sur-Moudon": { multiplier: 0.785, verified: "confirmed" },
    Chamblon: { multiplier: 0.66, verified: "confirmed" },
    Champagne: { multiplier: 0.65, verified: "confirmed" },
    Champtauroz: { multiplier: 0.77, verified: "confirmed" },
    Champvent: { multiplier: 0.7, verified: "confirmed" },
    Chardonne: { multiplier: 0.68, verified: "confirmed" },
    "Chavannes-de-Bogis": { multiplier: 0.58, verified: "confirmed" },
    "Chavannes-des-Bois": { multiplier: 0.66, verified: "confirmed" },
    "Chavannes-le-Chêne": { multiplier: 0.75, verified: "confirmed" },
    "Chavannes-le-Veyron": { multiplier: 0.77, verified: "confirmed" },
    "Chavannes-près-Renens": { multiplier: 0.775, verified: "confirmed" },
    "Chavannes-sur-Moudon": { multiplier: 0.7, verified: "confirmed" },
    Chavornay: { multiplier: 0.705, verified: "confirmed" },
    "Cheseaux-Noréaz": { multiplier: 0.67, verified: "confirmed" },
    "Cheseaux-sur-Lausanne": { multiplier: 0.73, verified: "confirmed" },
    Chessel: { multiplier: 0.65, verified: "confirmed" },
    Chevilly: { multiplier: 0.7, verified: "confirmed" },
    Chevroux: { multiplier: 0.685, verified: "confirmed" },
    Chexbres: { multiplier: 0.675, verified: "confirmed" },
    Chigny: { multiplier: 0.62, verified: "confirmed" },
    "Château-d'Oex": { multiplier: 0.815, verified: "confirmed" },
    Chéserex: { multiplier: 0.59, verified: "confirmed" },
    "Chêne-Pâquier": { multiplier: 0.75, verified: "confirmed" },
    Clarmont: { multiplier: 0.72, verified: "confirmed" },
    Coinsins: { multiplier: 0.49, verified: "confirmed" },
    Commugny: { multiplier: 0.58, verified: "confirmed" },
    Concise: { multiplier: 0.68, verified: "confirmed" },
    Coppet: { multiplier: 0.57, verified: "confirmed" },
    Corbeyrier: { multiplier: 0.74, verified: "confirmed" },
    "Corcelles-le-Jorat": { multiplier: 0.75, verified: "confirmed" },
    "Corcelles-près-Concise": { multiplier: 0.69, verified: "confirmed" },
    "Corcelles-près-Payerne": { multiplier: 0.65, verified: "confirmed" },
    Corseaux: { multiplier: 0.675, verified: "confirmed" },
    "Corsier-sur-Vevey": { multiplier: 0.645, verified: "confirmed" },
    Cossonay: { multiplier: 0.66, verified: "confirmed" },
    Crans: { multiplier: 0.59, verified: "confirmed" },
    Crassier: { multiplier: 0.65, verified: "confirmed" },
    Crissier: { multiplier: 0.635, verified: "confirmed" },
    Cronay: { multiplier: 0.75, verified: "confirmed" },
    Croy: { multiplier: 0.74, verified: "confirmed" },
    Cuarnens: { multiplier: 0.76, verified: "confirmed" },
    Cuarny: { multiplier: 0.73, verified: "confirmed" },
    Cudrefin: { multiplier: 0.59, verified: "confirmed" },
    Cugy: { multiplier: 0.76, verified: "confirmed" },
    Cully: { multiplier: 0.625, fiscalCommune: "Bourg-en-Lavaux", verified: "confirmed" },
    Curtilles: { multiplier: 0.71, verified: "confirmed" },
    Daillens: { multiplier: 0.66, verified: "confirmed" },
    Denens: { multiplier: 0.63, verified: "confirmed" },
    Denges: { multiplier: 0.62, verified: "confirmed" },
    Dizy: { multiplier: 0.75, verified: "confirmed" },
    Dompierre: { multiplier: 0.78, verified: "confirmed" },
    Donneloye: { multiplier: 0.73, verified: "confirmed" },
    Duillier: { multiplier: 0.66, verified: "confirmed" },
    Dully: { multiplier: 0.53, verified: "confirmed" },
    Démoret: { multiplier: 0.78, verified: "confirmed" },
    Echallens: { multiplier: 0.725, verified: "confirmed" },
    Echandens: { multiplier: 0.605, verified: "confirmed" },
    Echichens: { multiplier: 0.66, verified: "confirmed" },
    Eclépens: { multiplier: 0.46, verified: "confirmed" },
    Ecublens: { multiplier: 0.625, verified: "confirmed" },
    Epalinges: { multiplier: 0.645, verified: "confirmed" },
    Ependes: { multiplier: 0.735, verified: "confirmed" },
    "Essertines-sur-Rolle": { multiplier: 0.665, verified: "confirmed" },
    "Essertines-sur-Yverdon": { multiplier: 0.72, verified: "confirmed" },
    Etagnières: { multiplier: 0.73, verified: "confirmed" },
    Etoy: { multiplier: 0.6, verified: "confirmed" },
    Eysins: { multiplier: 0.595, verified: "confirmed" },
    Faoug: { multiplier: 0.65, verified: "confirmed" },
    Ferreyres: { multiplier: 0.76, verified: "confirmed" },
    Fey: { multiplier: 0.75, verified: "confirmed" },
    Fiez: { multiplier: 0.69, verified: "confirmed" },
    "Fontaines-sur-Grandson": { multiplier: 0.72, verified: "confirmed" },
    "Forel (Lavaux)": { multiplier: 0.69, verified: "confirmed" },
    Founex: { multiplier: 0.57, verified: "confirmed" },
    Froideville: { multiplier: 0.72, verified: "confirmed" },
    Féchy: { multiplier: 0.64, verified: "confirmed" },
    Genolier: { multiplier: 0.52, verified: "confirmed" },
    Giez: { multiplier: 0.69, verified: "confirmed" },
    Gilly: { multiplier: 0.625, verified: "confirmed" },
    Gimel: { multiplier: 0.73, verified: "confirmed" },
    Gingins: { multiplier: 0.6, verified: "confirmed" },
    Givrins: { multiplier: 0.685, verified: "confirmed" },
    Gland: { multiplier: 0.61, verified: "confirmed" },
    Gollion: { multiplier: 0.74, verified: "confirmed" },
    Goumoëns: { multiplier: 0.755, verified: "confirmed" },
    Grancy: { multiplier: 0.7, verified: "confirmed" },
    Grandcour: { multiplier: 0.72, verified: "confirmed" },
    Grandevent: { multiplier: 0.71, verified: "confirmed" },
    Grandson: { multiplier: 0.69, verified: "confirmed" },
    Grens: { multiplier: 0.6, verified: "confirmed" },
    Gryon: { multiplier: 0.735, verified: "confirmed" },
    Hautemorges: { multiplier: 0.68, verified: "confirmed" },
    Henniez: { multiplier: 0.69, verified: "confirmed" },
    Hermenches: { multiplier: 0.78, verified: "confirmed" },
    Jongny: { multiplier: 0.695, verified: "confirmed" },
    "Jorat-Menthue": { multiplier: 0.705, verified: "confirmed" },
    "Jorat-Mézières": { multiplier: 0.71, verified: "confirmed" },
    "Jouxtens-Mézery": { multiplier: 0.59, verified: "confirmed" },
    Juriens: { multiplier: 0.79, verified: "confirmed" },
    "L'Abbaye": { multiplier: 0.76, verified: "confirmed" },
    "L'Abergement": { multiplier: 0.8, verified: "confirmed" },
    "L'Isle": { multiplier: 0.75, verified: "confirmed" },
    "L'Orient (fraction)": { multiplier: 0.1, verified: "confirmed" },
    "La Chaux (Cossonay)": { multiplier: 0.76, verified: "confirmed" },
    "La Praz": { multiplier: 0.83, verified: "confirmed" },
    "La Rippe": { multiplier: 0.635, verified: "confirmed" },
    "La Sarraz": { multiplier: 0.7, verified: "confirmed" },
    "La Tour-de-Peilz": { multiplier: 0.64, verified: "confirmed" },
    Lausanne: { multiplier: 0.785, verified: "confirmed" },
    "Lavey-Morcles": { multiplier: 0.715, verified: "confirmed" },
    Lavigny: { multiplier: 0.73, verified: "confirmed" },
    "Le Brassus (fraction)": { multiplier: 0.08, verified: "confirmed" },
    "Le Chenit": { multiplier: 0.585, verified: "confirmed" },
    "Le Lieu": { multiplier: 0.7, verified: "confirmed" },
    "Le Mont-sur-Lausanne": { multiplier: 0.72, verified: "confirmed" },
    "Le Sentier (fraction)": { multiplier: 0.08, verified: "confirmed" },
    "Le Vaud": { multiplier: 0.69, verified: "confirmed" },
    "Les Bioux (fraction)": { multiplier: 0.03, verified: "confirmed" },
    "Les Clées": { multiplier: 0.8, verified: "confirmed" },
    Leysin: { multiplier: 0.78, verified: "confirmed" },
    Lignerolle: { multiplier: 0.785, verified: "confirmed" },
    Lonay: { multiplier: 0.55, verified: "confirmed" },
    Longirod: { multiplier: 0.775, verified: "confirmed" },
    Lovatens: { multiplier: 0.75, verified: "confirmed" },
    Lucens: { multiplier: 0.695, verified: "confirmed" },
    Luins: { multiplier: 0.585, verified: "confirmed" },
    Lully: { multiplier: 0.58, verified: "confirmed" },
    "Lussery-Villars": { multiplier: 0.75, verified: "confirmed" },
    "Lussy-sur-Morges": { multiplier: 0.615, verified: "confirmed" },
    Lutry: { multiplier: 0.54, verified: "confirmed" },
    Maracon: { multiplier: 0.745, verified: "confirmed" },
    Marchissy: { multiplier: 0.775, verified: "confirmed" },
    Mathod: { multiplier: 0.72, verified: "confirmed" },
    Mauborget: { multiplier: 0.7, verified: "confirmed" },
    Mauraz: { multiplier: 0.75, verified: "confirmed" },
    Mex: { multiplier: 0.595, verified: "confirmed" },
    Mies: { multiplier: 0.54, verified: "confirmed" },
    Missy: { multiplier: 0.69, verified: "confirmed" },
    Moiry: { multiplier: 0.76, verified: "confirmed" },
    Mollens: { multiplier: 0.74, verified: "confirmed" },
    Molondin: { multiplier: 0.81, verified: "confirmed" },
    "Mont-la-Ville": { multiplier: 0.76, verified: "confirmed" },
    "Mont-sur-Rolle": { multiplier: 0.62, verified: "confirmed" },
    "Montagny-près-Yverdon": { multiplier: 0.645, verified: "confirmed" },
    Montanaire: { multiplier: 0.7, verified: "confirmed" },
    Montcherand: { multiplier: 0.72, verified: "confirmed" },
    Montilliez: { multiplier: 0.725, verified: "confirmed" },
    Montpreveyres: { multiplier: 0.745, verified: "confirmed" },
    Montreux: { multiplier: 0.65, verified: "confirmed" },
    Montricher: { multiplier: 0.64, verified: "confirmed" },
    Morges: { multiplier: 0.67, verified: "confirmed" },
    Morrens: { multiplier: 0.74, verified: "confirmed" },
    Moudon: { multiplier: 0.725, verified: "confirmed" },
    Mutrux: { multiplier: 0.8, verified: "confirmed" },
    Novalles: { multiplier: 0.76, verified: "confirmed" },
    Noville: { multiplier: 0.75, verified: "confirmed" },
    Nyon: { multiplier: 0.61, verified: "confirmed" },
    Ogens: { multiplier: 0.76, verified: "confirmed" },
    Ollon: { multiplier: 0.68, verified: "confirmed" },
    Onnens: { multiplier: 0.65, verified: "confirmed" },
    Oppens: { multiplier: 0.79, verified: "confirmed" },
    Orbe: { multiplier: 0.755, verified: "confirmed" },
    Orges: { multiplier: 0.74, verified: "confirmed" },
    "Ormont-Dessous": { multiplier: 0.77, verified: "confirmed" },
    "Ormont-Dessus": { multiplier: 0.76, verified: "confirmed" },
    Orny: { multiplier: 0.73, verified: "confirmed" },
    Oron: { multiplier: 0.69, verified: "confirmed" },
    Orzens: { multiplier: 0.79, verified: "confirmed" },
    "Oulens-sous-Echallens": { multiplier: 0.71, verified: "confirmed" },
    Pailly: { multiplier: 0.76, verified: "confirmed" },
    Paudex: { multiplier: 0.665, verified: "confirmed" },
    Payerne: { multiplier: 0.7, verified: "confirmed" },
    Penthalaz: { multiplier: 0.725, verified: "confirmed" },
    Penthaz: { multiplier: 0.695, verified: "confirmed" },
    Penthéréaz: { multiplier: 0.74, verified: "confirmed" },
    Perroy: { multiplier: 0.605, verified: "confirmed" },
    "Poliez-Pittet": { multiplier: 0.73, verified: "confirmed" },
    Pompaples: { multiplier: 0.66, verified: "confirmed" },
    Pomy: { multiplier: 0.71, verified: "confirmed" },
    Prangins: { multiplier: 0.57, verified: "confirmed" },
    Premier: { multiplier: 0.795, verified: "confirmed" },
    Prilly: { multiplier: 0.725, verified: "confirmed" },
    Provence: { multiplier: 0.81, verified: "confirmed" },
    Préverenges: { multiplier: 0.65, verified: "confirmed" },
    Prévonloup: { multiplier: 0.725, verified: "confirmed" },
    Puidoux: { multiplier: 0.685, verified: "confirmed" },
    Pully: { multiplier: 0.61, verified: "confirmed" },
    Rances: { multiplier: 0.765, verified: "confirmed" },
    Renens: { multiplier: 0.77, verified: "confirmed" },
    Rennaz: { multiplier: 0.64, verified: "confirmed" },
    Rivaz: { multiplier: 0.62, verified: "confirmed" },
    Roche: { multiplier: 0.665, verified: "confirmed" },
    Rolle: { multiplier: 0.595, verified: "confirmed" },
    "Romainmôtier-Envy": { multiplier: 0.81, verified: "confirmed" },
    "Romanel-sur-Lausanne": { multiplier: 0.705, verified: "confirmed" },
    "Romanel-sur-Morges": { multiplier: 0.56, verified: "confirmed" },
    Ropraz: { multiplier: 0.775, verified: "confirmed" },
    Rossenges: { multiplier: 0.65, verified: "confirmed" },
    Rossinière: { multiplier: 0.81, verified: "confirmed" },
    Rougemont: { multiplier: 0.79, verified: "confirmed" },
    Rovray: { multiplier: 0.73, verified: "confirmed" },
    Rueyres: { multiplier: 0.73, verified: "confirmed" },
    "Saint-Barthélemy": { multiplier: 0.77, verified: "confirmed" },
    "Saint-Cergue": { multiplier: 0.66, verified: "confirmed" },
    "Saint-George": { multiplier: 0.695, verified: "confirmed" },
    "Saint-Livres": { multiplier: 0.69, verified: "confirmed" },
    "Saint-Oyens": { multiplier: 0.77, verified: "confirmed" },
    "Saint-Prex": { multiplier: 0.59, verified: "confirmed" },
    "Saint-Sulpice": { multiplier: 0.55, verified: "confirmed" },
    "Sainte-Croix": { multiplier: 0.7, verified: "confirmed" },
    Saubraz: { multiplier: 0.77, verified: "confirmed" },
    Savigny: { multiplier: 0.69, verified: "confirmed" },
    Senarclens: { multiplier: 0.685, verified: "confirmed" },
    Sergey: { multiplier: 0.76, verified: "confirmed" },
    Servion: { multiplier: 0.69, verified: "confirmed" },
    "Signy-Avenex": { multiplier: 0.58, verified: "confirmed" },
    "St-Saphorin (Lavaux)": { multiplier: 0.74, verified: "confirmed" },
    Suchy: { multiplier: 0.7, verified: "confirmed" },
    Sullens: { multiplier: 0.64, verified: "confirmed" },
    Suscévaz: { multiplier: 0.72, verified: "confirmed" },
    Syens: { multiplier: 0.65, verified: "confirmed" },
    Tannay: { multiplier: 0.605, verified: "confirmed" },
    Tartegnin: { multiplier: 0.79, verified: "confirmed" },
    Tolochenaz: { multiplier: 0.64, verified: "confirmed" },
    Trey: { multiplier: 0.78, verified: "confirmed" },
    Treycovagnes: { multiplier: 0.73, verified: "confirmed" },
    Treytorrens: { multiplier: 0.815, verified: "confirmed" },
    Trélex: { multiplier: 0.57, verified: "confirmed" },
    Tévenon: { multiplier: 0.715, verified: "confirmed" },
    Ursins: { multiplier: 0.75, verified: "confirmed" },
    Valbroye: { multiplier: 0.705, verified: "confirmed" },
    "Valeyres-sous-Montagny": { multiplier: 0.705, verified: "confirmed" },
    "Valeyres-sous-Rances": { multiplier: 0.71, verified: "confirmed" },
    "Valeyres-sous-Ursins": { multiplier: 0.77, verified: "confirmed" },
    Vallorbe: { multiplier: 0.7, verified: "confirmed" },
    Vaulion: { multiplier: 0.81, verified: "confirmed" },
    "Vaux-sur-Morges": { multiplier: 0.56, verified: "confirmed" },
    Vevey: { multiplier: 0.745, verified: "confirmed" },
    Veytaux: { multiplier: 0.65, verified: "confirmed" },
    Vich: { multiplier: 0.63, verified: "confirmed" },
    "Villars-Epeney": { multiplier: 0.72, verified: "confirmed" },
    "Villars-Sainte-Croix": { multiplier: 0.605, verified: "confirmed" },
    "Villars-le-Comte": { multiplier: 0.68, verified: "confirmed" },
    "Villars-le-Terroir": { multiplier: 0.76, verified: "confirmed" },
    "Villars-sous-Yens": { multiplier: 0.74, verified: "confirmed" },
    Villarzel: { multiplier: 0.75, verified: "confirmed" },
    Villeneuve: { multiplier: 0.665, verified: "confirmed" },
    Vinzel: { multiplier: 0.65, verified: "confirmed" },
    Vuarrens: { multiplier: 0.735, verified: "confirmed" },
    Vucherens: { multiplier: 0.75, verified: "confirmed" },
    "Vufflens-la-Ville": { multiplier: 0.65, verified: "confirmed" },
    "Vufflens-le-Château": { multiplier: 0.605, verified: "confirmed" },
    "Vugelles-La Mothe": { multiplier: 0.7, verified: "confirmed" },
    Vuiteboeuf: { multiplier: 0.75, verified: "confirmed" },
    Vulliens: { multiplier: 0.74, verified: "confirmed" },
    Vullierens: { multiplier: 0.76, verified: "confirmed" },
    "Vully-les-Lacs": { multiplier: 0.67, verified: "confirmed" },
    Yens: { multiplier: 0.68, verified: "confirmed" },
    "Yverdon-les-Bains": { multiplier: 0.75, verified: "confirmed" },
    Yvonand: { multiplier: 0.73, verified: "confirmed" },
    Yvorne: { multiplier: 0.715, verified: "confirmed" },
  },
  VS: {
    Agarn: { multiplier: 1.3, verified: "confirmed", vsIndexationPercent: 153 },
    Albinen: { multiplier: 1.3, verified: "confirmed", vsIndexationPercent: 145 },
    Anniviers: { multiplier: 1.25, verified: "confirmed", vsIndexationPercent: 146 },
    Arbaz: { multiplier: 1.25, verified: "confirmed", vsIndexationPercent: 146 },
    Ardon: { multiplier: 1.3, verified: "confirmed", vsIndexationPercent: 166 },
    Ausserberg: { multiplier: 1.3, verified: "confirmed", vsIndexationPercent: 138 },
    Ayent: { multiplier: 1.3, verified: "confirmed", vsIndexationPercent: 158 },
    Bagnes: {
      multiplier: 1,
      fiscalCommune: "Val de Bagnes",
      verified: "confirmed",
      vsIndexationPercent: 176,
    },
    Baltschieder: { multiplier: 1.2, verified: "confirmed", vsIndexationPercent: 166 },
    Bellwald: { multiplier: 1.3, verified: "confirmed", vsIndexationPercent: 160 },
    Bettmeralp: { multiplier: 1.2, verified: "confirmed", vsIndexationPercent: 136 },
    Binn: { multiplier: 1.2, verified: "confirmed", vsIndexationPercent: 156 },
    Bister: { multiplier: 1, verified: "confirmed", vsIndexationPercent: 176 },
    Bitsch: { multiplier: 1, verified: "confirmed", vsIndexationPercent: 176 },
    Blatten: { multiplier: 1.4, verified: "confirmed", vsIndexationPercent: 136 },
    "Bourg-Saint-Pierre": { multiplier: 1, verified: "confirmed", vsIndexationPercent: 176 },
    Bovernier: { multiplier: 1.2, verified: "confirmed", vsIndexationPercent: 156 },
    "Brig/Glis": { multiplier: 1, verified: "confirmed", vsIndexationPercent: 176 },
    "Brigue-Glis": {
      multiplier: 1,
      fiscalCommune: "Brig/Glis",
      verified: "confirmed",
      vsIndexationPercent: 176,
    },
    Bürchen: { multiplier: 1.3, verified: "confirmed", vsIndexationPercent: 146 },
    Chalais: { multiplier: 1.3, verified: "confirmed", vsIndexationPercent: 146 },
    Chamoson: { multiplier: 1.25, verified: "confirmed", vsIndexationPercent: 143 },
    Champéry: { multiplier: 1.35, verified: "confirmed", vsIndexationPercent: 141 },
    Chippis: { multiplier: 1.2, verified: "confirmed", vsIndexationPercent: 146 },
    "Collombey-Muraz": { multiplier: 1.25, verified: "confirmed", vsIndexationPercent: 171 },
    Collonges: { multiplier: 1.1, verified: "confirmed", vsIndexationPercent: 165 },
    Conthey: { multiplier: 1.2, verified: "confirmed", vsIndexationPercent: 163 },
    "Crans-Montana": { multiplier: 1.15, verified: "confirmed", vsIndexationPercent: 176 },
    Dorénaz: { multiplier: 1.2, verified: "confirmed", vsIndexationPercent: 161 },
    Eggerberg: { multiplier: 1.3, verified: "confirmed", vsIndexationPercent: 133 },
    Eischoll: { multiplier: 1.3, verified: "confirmed", vsIndexationPercent: 146 },
    Eisten: { multiplier: 1, verified: "confirmed", vsIndexationPercent: 176 },
    Embd: { multiplier: 1.3, verified: "confirmed", vsIndexationPercent: 158 },
    Ergisch: { multiplier: 1, verified: "confirmed", vsIndexationPercent: 176 },
    Ernen: { multiplier: 1.1, verified: "confirmed", vsIndexationPercent: 176 },
    Evolène: { multiplier: 1.25, verified: "confirmed", vsIndexationPercent: 140 },
    Ferden: { multiplier: 1.4, verified: "confirmed", vsIndexationPercent: 151 },
    Fiesch: { multiplier: 1.15, verified: "confirmed", vsIndexationPercent: 160 },
    Fieschertal: { multiplier: 1.1, verified: "confirmed", vsIndexationPercent: 176 },
    Finhaut: { multiplier: 1, verified: "confirmed", vsIndexationPercent: 176 },
    Fully: { multiplier: 1.2, verified: "confirmed", vsIndexationPercent: 165 },
    "Gampel-Bratsch": { multiplier: 1.3, verified: "confirmed", vsIndexationPercent: 151 },
    Goms: { multiplier: 1.1, verified: "confirmed", vsIndexationPercent: 173 },
    Grengiols: { multiplier: 1, verified: "confirmed", vsIndexationPercent: 146 },
    Grimisuat: { multiplier: 1.25, verified: "confirmed", vsIndexationPercent: 163 },
    Grächen: { multiplier: 1.4, verified: "confirmed", vsIndexationPercent: 135 },
    Grône: { multiplier: 1.25, verified: "confirmed", vsIndexationPercent: 143 },
    "Guttet-Feschel": { multiplier: 1.3, verified: "confirmed", vsIndexationPercent: 148 },
    Hérémence: { multiplier: 1, verified: "confirmed", vsIndexationPercent: 176 },
    Icogne: { multiplier: 1.2, verified: "confirmed", vsIndexationPercent: 176 },
    Inden: { multiplier: 1.1, verified: "confirmed", vsIndexationPercent: 136 },
    Isérables: { multiplier: 1.35, verified: "confirmed", vsIndexationPercent: 138 },
    Kippel: { multiplier: 1.4, verified: "confirmed", vsIndexationPercent: 136 },
    Lalden: { multiplier: 1.2, verified: "confirmed", vsIndexationPercent: 158 },
    Lax: { multiplier: 1.4, verified: "confirmed", vsIndexationPercent: 163 },
    Lens: { multiplier: 1.05, verified: "confirmed", vsIndexationPercent: 176 },
    Leuk: { multiplier: 1.3, verified: "confirmed", vsIndexationPercent: 156 },
    Leukerbad: { multiplier: 1.45, verified: "confirmed", vsIndexationPercent: 151 },
    Leytron: { multiplier: 1.2, verified: "confirmed", vsIndexationPercent: 146 },
    Liddes: { multiplier: 1.25, verified: "confirmed", vsIndexationPercent: 143 },
    Martigny: { multiplier: 1.1, verified: "confirmed", vsIndexationPercent: 166 },
    "Martigny-Combe": { multiplier: 1.1, verified: "confirmed", vsIndexationPercent: 163 },
    Massongex: { multiplier: 1.2, verified: "confirmed", vsIndexationPercent: 168 },
    "Mont-Noble": { multiplier: 1.35, verified: "confirmed", vsIndexationPercent: 148 },
    Monthey: { multiplier: 1.2, verified: "confirmed", vsIndexationPercent: 170 },
    "Mörel-Filet": { multiplier: 1.15, verified: "confirmed", vsIndexationPercent: 140 },
    Naters: { multiplier: 1.1, verified: "confirmed", vsIndexationPercent: 176 },
    Nendaz: { multiplier: 1.3, verified: "confirmed", vsIndexationPercent: 156 },
    Niedergesteln: { multiplier: 1.2, verified: "confirmed", vsIndexationPercent: 156 },
    "Noble-Contrée": { multiplier: 1.1, verified: "confirmed", vsIndexationPercent: 166 },
    Oberems: { multiplier: 1, verified: "confirmed", vsIndexationPercent: 176 },
    Obergoms: { multiplier: 1.1, verified: "confirmed", vsIndexationPercent: 176 },
    Orsières: { multiplier: 1.2, verified: "confirmed", vsIndexationPercent: 150 },
    "Port-Valais": { multiplier: 1.1, verified: "confirmed", vsIndexationPercent: 170 },
    Randa: { multiplier: 1.1, verified: "confirmed", vsIndexationPercent: 176 },
    Raron: { multiplier: 1.2, verified: "confirmed", vsIndexationPercent: 165 },
    Riddes: { multiplier: 1.25, verified: "confirmed", vsIndexationPercent: 153 },
    "Ried-Brig": { multiplier: 1.1, verified: "confirmed", vsIndexationPercent: 170 },
    Riederalp: { multiplier: 1.2, verified: "confirmed", vsIndexationPercent: 138 },
    "Saas-Almagell": { multiplier: 1.2, verified: "confirmed", vsIndexationPercent: 150 },
    "Saas-Balen": { multiplier: 1.1, verified: "confirmed", vsIndexationPercent: 153 },
    "Saas-Fee": { multiplier: 1.2, verified: "confirmed", vsIndexationPercent: 145 },
    "Saas-Grund": { multiplier: 1.3, verified: "confirmed", vsIndexationPercent: 133 },
    Saillon: { multiplier: 1.2, verified: "confirmed", vsIndexationPercent: 146 },
    "Saint-Gingolph": { multiplier: 1.35, verified: "confirmed", vsIndexationPercent: 133 },
    "Saint-Léonard": { multiplier: 1.2, verified: "confirmed", vsIndexationPercent: 158 },
    "Saint-Martin": { multiplier: 1.35, verified: "confirmed", vsIndexationPercent: 150 },
    "Saint-Maurice": { multiplier: 1.25, verified: "confirmed", vsIndexationPercent: 163 },
    Salgesch: { multiplier: 1.2, verified: "confirmed", vsIndexationPercent: 136 },
    Salvan: { multiplier: 1.15, verified: "confirmed", vsIndexationPercent: 173 },
    Savièse: { multiplier: 1.15, verified: "confirmed", vsIndexationPercent: 156 },
    Saxon: { multiplier: 1.2, verified: "confirmed", vsIndexationPercent: 166 },
    Sembrancher: { multiplier: 1.2, verified: "confirmed", vsIndexationPercent: 155 },
    Sierre: { multiplier: 1.2, verified: "confirmed", vsIndexationPercent: 161 },
    Simplon: { multiplier: 1, verified: "confirmed", vsIndexationPercent: 176 },
    // Chef-lieu cantonal : coefficient déjà utilisé comme repli par défaut
    // (CANTON_SCALES.VS.communalMultiplierCapital dans cantons.ts).
    // vsIndexationPercent initialement calibré par recherche numérique
    // contre un cas réel AFC (swisstaxcalculator.estv.admin.ch, Sion,
    // personne seule, 0 enfant, 80'000 CHF brut) : reproduit 4'342.15 CHF
    // contre 4'342 CHF réels (écart 0.15 CHF) — voir cantons.test.ts.
    // Valeur 176% depuis confirmée exactement par le document officiel
    // "Coefficients et indexations des communes valaisannes 2022-2027".
    Sion: { multiplier: 1.1, verified: "confirmed", vsIndexationPercent: 176 },
    "St. Niklaus": { multiplier: 1.2, verified: "confirmed", vsIndexationPercent: 160 },
    Stalden: { multiplier: 1.1, verified: "confirmed", vsIndexationPercent: 171 },
    Staldenried: { multiplier: 1.1, verified: "confirmed", vsIndexationPercent: 176 },
    "Steg-Hohtenn": { multiplier: 1.2, verified: "confirmed", vsIndexationPercent: 156 },
    Termen: { multiplier: 1.2, verified: "confirmed", vsIndexationPercent: 176 },
    Trient: { multiplier: 1, verified: "confirmed", vsIndexationPercent: 176 },
    Troistorrents: { multiplier: 1.2, verified: "confirmed", vsIndexationPercent: 166 },
    "Turtmann-Unterems": { multiplier: 1.2, verified: "confirmed", vsIndexationPercent: 166 },
    Täsch: { multiplier: 1.1, verified: "confirmed", vsIndexationPercent: 155 },
    Törbel: { multiplier: 1.4, verified: "confirmed", vsIndexationPercent: 176 },
    Unterbäch: { multiplier: 1.2, verified: "confirmed", vsIndexationPercent: 138 },
    "Val d'Illiez": { multiplier: 1.3, verified: "confirmed", vsIndexationPercent: 151 },
    "Val de Bagnes": { multiplier: 1, verified: "confirmed", vsIndexationPercent: 176 },
    Varen: { multiplier: 1.2, verified: "confirmed", vsIndexationPercent: 156 },
    Verbier: {
      multiplier: 1,
      fiscalCommune: "Val de Bagnes",
      verified: "confirmed",
      vsIndexationPercent: 176,
    },
    Vernayaz: { multiplier: 1.2, verified: "confirmed", vsIndexationPercent: 166 },
    Vex: { multiplier: 1.3, verified: "confirmed", vsIndexationPercent: 166 },
    Veysonnaz: { multiplier: 1.2, verified: "confirmed", vsIndexationPercent: 110 },
    Vionnaz: { multiplier: 1.1, verified: "confirmed", vsIndexationPercent: 153 },
    Visp: { multiplier: 1.1, verified: "confirmed", vsIndexationPercent: 166 },
    Visperterminen: { multiplier: 1.3, verified: "confirmed", vsIndexationPercent: 150 },
    Viège: {
      multiplier: 1.1,
      fiscalCommune: "Visp",
      verified: "confirmed",
      vsIndexationPercent: 166,
    },
    Vouvry: { multiplier: 1.25, verified: "confirmed", vsIndexationPercent: 158 },
    Vérossaz: { multiplier: 1.3, verified: "confirmed", vsIndexationPercent: 153 },
    Vétroz: { multiplier: 1.15, verified: "confirmed", vsIndexationPercent: 163 },
    Wiler: { multiplier: 1.4, verified: "confirmed", vsIndexationPercent: 146 },
    Zeneggen: { multiplier: 1.3, verified: "confirmed", vsIndexationPercent: 151 },
    Zermatt: { multiplier: 1, verified: "confirmed", vsIndexationPercent: 176 },
    Zwischbergen: { multiplier: 1, verified: "confirmed", vsIndexationPercent: 173 },
    Évionnaz: { multiplier: 1.3, verified: "confirmed", vsIndexationPercent: 176 },
  },
  FR: {
    Attalens: { multiplier: 0.785, verified: "confirmed" },
    Autigny: { multiplier: 0.9, verified: "confirmed" },
    Avry: { multiplier: 0.691, verified: "confirmed" },
    "Bas-Intyamon": { multiplier: 0.832, verified: "confirmed" },
    Belfaux: { multiplier: 0.84, verified: "confirmed" },
    "Belmont-Broye": { multiplier: 0.78, verified: "confirmed" },
    "Billens-Hennens": { multiplier: 0.95, verified: "confirmed" },
    "Bois-d'Amont": { multiplier: 0.85, verified: "confirmed" },
    Bossonnens: { multiplier: 0.9, verified: "confirmed" },
    Botterens: { multiplier: 0.85, verified: "confirmed" },
    Broc: { multiplier: 0.92, verified: "confirmed" },
    Brünisried: { multiplier: 0.84, verified: "confirmed" },
    Bulle: { multiplier: 0.743, verified: "confirmed" },
    Bösingen: { multiplier: 0.76, verified: "confirmed" },
    "Cheyres-Châbles": { multiplier: 0.7, verified: "confirmed" },
    "Châtel-Saint-Denis": { multiplier: 0.836, verified: "confirmed" },
    "Châtel-sur-Montsalvens": { multiplier: 0.795, verified: "confirmed" },
    Châtillon: { multiplier: 0.65, verified: "confirmed" },
    Châtonnaye: { multiplier: 0.85, verified: "confirmed" },
    Chénens: { multiplier: 0.917, verified: "confirmed" },
    Corbières: { multiplier: 0.735, verified: "confirmed" },
    Corminboeuf: { multiplier: 0.75, verified: "confirmed" },
    Cottens: { multiplier: 0.8, verified: "confirmed" },
    Courgevaux: { multiplier: 0.76, verified: "confirmed" },
    Courtepin: { multiplier: 0.8, verified: "confirmed" },
    Cressier: { multiplier: 0.68, verified: "confirmed" },
    Crésuz: { multiplier: 0.67, verified: "confirmed" },
    Cugy: { multiplier: 0.85, verified: "confirmed" },
    "Delley-Portalban": { multiplier: 0.499, verified: "confirmed" },
    Düdingen: { multiplier: 0.82, verified: "confirmed" },
    Echarlens: { multiplier: 0.7, verified: "confirmed" },
    Estavayer: { multiplier: 0.84, verified: "confirmed" },
    Ferpicloz: { multiplier: 0.55, verified: "confirmed" },
    Fribourg: { multiplier: 0.8, verified: "confirmed" },
    Fräschels: { multiplier: 0.75, verified: "confirmed" },
    "Fétigny-Ménières": { multiplier: 0.86, verified: "confirmed" },
    Gibloux: { multiplier: 0.82, verified: "confirmed" },
    Giffers: { multiplier: 0.859, verified: "confirmed" },
    Givisiez: { multiplier: 0.7, verified: "confirmed" },
    Gletterens: { multiplier: 0.689, verified: "confirmed" },
    Grandvillard: { multiplier: 0.8, verified: "confirmed" },
    "Granges (Veveyse)": { multiplier: 0.84, verified: "confirmed" },
    "Granges-Paccot": { multiplier: 0.678, verified: "confirmed" },
    Grangettes: { multiplier: 0.85, verified: "confirmed" },
    Greng: { multiplier: 0.32, verified: "confirmed" },
    "Grolley-Ponthaux": { multiplier: 0.8, verified: "confirmed" },
    Gruyères: { multiplier: 0.8, verified: "confirmed" },
    Guin: { multiplier: 0.82, verified: "confirmed" },
    Gurmels: { multiplier: 0.8, verified: "confirmed" },
    "Haut-Intyamon": { multiplier: 0.97, verified: "confirmed" },
    Hauterive: { multiplier: 0.74, verified: "confirmed" },
    Hauteville: { multiplier: 0.777, verified: "confirmed" },
    Heitenried: { multiplier: 0.81, verified: "confirmed" },
    Jaun: { multiplier: 1, verified: "confirmed" },
    Kerzers: { multiplier: 0.79, verified: "confirmed" },
    Kleinbösingen: { multiplier: 0.75, verified: "confirmed" },
    "La Brillaz": { multiplier: 0.85, verified: "confirmed" },
    "La Roche": { multiplier: 0.87, verified: "confirmed" },
    "La Sonnaz": { multiplier: 0.76, verified: "confirmed" },
    "La Verrerie": { multiplier: 0.86, verified: "confirmed" },
    "Le Châtelard": { multiplier: 0.9, verified: "confirmed" },
    "Le Flon": { multiplier: 0.938, verified: "confirmed" },
    "Le Mouret": { multiplier: 0.845, verified: "confirmed" },
    "Le Pâquier": { multiplier: 0.8, verified: "confirmed" },
    "Les Montets": { multiplier: 0.774, verified: "confirmed" },
    Lully: { multiplier: 0.85, verified: "confirmed" },
    Marly: { multiplier: 0.89, verified: "confirmed" },
    Marsens: { multiplier: 0.75, verified: "confirmed" },
    Massonnens: { multiplier: 0.912, verified: "confirmed" },
    Matran: { multiplier: 0.65, verified: "confirmed" },
    Meyriez: { multiplier: 0.58, verified: "confirmed" },
    "Misery-Courtion": { multiplier: 0.88, verified: "confirmed" },
    "Mont-Vully": { multiplier: 0.58, verified: "confirmed" },
    Montagny: { multiplier: 0.836, verified: "confirmed" },
    Morlon: { multiplier: 0.843, verified: "confirmed" },
    Muntelier: { multiplier: 0.55, verified: "confirmed" },
    Murten: { multiplier: 0.62, verified: "confirmed" },
    Mézières: { multiplier: 0.93, verified: "confirmed" },
    Neyruz: { multiplier: 0.81, verified: "confirmed" },
    Nuvilly: { multiplier: 0.879, verified: "confirmed" },
    Pierrafortscha: { multiplier: 0.8, verified: "confirmed" },
    Plaffeien: { multiplier: 0.92, verified: "confirmed" },
    Plasselb: { multiplier: 0.95, verified: "confirmed" },
    "Pont-en-Ogoz": { multiplier: 0.75, verified: "confirmed" },
    "Pont-la-Ville": { multiplier: 0.75, verified: "confirmed" },
    Prez: { multiplier: 0.8, verified: "confirmed" },
    Prévondavaux: { multiplier: 0.903, verified: "confirmed" },
    Rechthalten: { multiplier: 0.86, verified: "confirmed" },
    Remaufens: { multiplier: 0.88, verified: "confirmed" },
    Riaz: { multiplier: 0.73, verified: "confirmed" },
    "Ried bei Kerzers": { multiplier: 0.725, verified: "confirmed" },
    Romont: { multiplier: 0.9, verified: "confirmed" },
    Rue: { multiplier: 0.77, verified: "confirmed" },
    "Saint-Aubin": { multiplier: 0.8, verified: "confirmed" },
    "Saint-Martin": { multiplier: 0.87, verified: "confirmed" },
    Schmitten: { multiplier: 0.77, verified: "confirmed" },
    Semsales: { multiplier: 0.83, verified: "confirmed" },
    Siviriez: { multiplier: 0.88, verified: "confirmed" },
    Sorens: { multiplier: 0.73, verified: "confirmed" },
    "St. Silvester": { multiplier: 0.95, verified: "confirmed" },
    "St. Ursen": { multiplier: 0.75, verified: "confirmed" },
    Surpierre: { multiplier: 0.887, verified: "confirmed" },
    Sâles: { multiplier: 0.86, verified: "confirmed" },
    Sévaz: { multiplier: 0.5, verified: "confirmed" },
    Tafers: { multiplier: 0.75, verified: "confirmed" },
    Tentlingen: { multiplier: 0.86, verified: "confirmed" },
    Torny: { multiplier: 0.85, verified: "confirmed" },
    Treyvaux: { multiplier: 0.8, verified: "confirmed" },
    Ueberstorf: { multiplier: 0.87, verified: "confirmed" },
    Ursy: { multiplier: 0.89, verified: "confirmed" },
    "Val-de-Charmey": { multiplier: 0.898, verified: "confirmed" },
    Vallon: { multiplier: 0.83, verified: "confirmed" },
    Vaulruz: { multiplier: 0.79, verified: "confirmed" },
    "Villars-sur-Glâne": { multiplier: 0.639, verified: "confirmed" },
    "Villarsel-sur-Marly": { multiplier: 0.9, verified: "confirmed" },
    Villaz: { multiplier: 0.88, verified: "confirmed" },
    Villorsonnens: { multiplier: 0.8, verified: "confirmed" },
    Vuadens: { multiplier: 0.828, verified: "confirmed" },
    "Vuisternens-devant-Romont": { multiplier: 0.92, verified: "confirmed" },
    "Wünnewil-Flamatt": { multiplier: 0.82, verified: "confirmed" },
  },
  NE: {
    Boudry: { multiplier: 0.68, verified: "confirmed" },
    "Brot-Plamboz": { multiplier: 0.75, verified: "confirmed" },
    Cernier: { multiplier: 0.66, fiscalCommune: "Val-de-Ruz", verified: "confirmed" },
    Colombier: { multiplier: 0.63, fiscalCommune: "Milvignes", verified: "confirmed" },
    Cornaux: { multiplier: 0.74, verified: "confirmed" },
    Cortaillod: { multiplier: 0.66, verified: "confirmed" },
    Couvet: { multiplier: 0.76, fiscalCommune: "Val-de-Travers", verified: "confirmed" },
    Cressier: { multiplier: 0.77, verified: "confirmed" },
    Enges: { multiplier: 0.68, fiscalCommune: "Laténa", verified: "confirmed" },
    Fleurier: { multiplier: 0.76, fiscalCommune: "Val-de-Travers", verified: "confirmed" },
    Hauterive: { multiplier: 0.68, fiscalCommune: "Laténa", verified: "confirmed" },
    "La Brévine": { multiplier: 0.75, verified: "confirmed" },
    "La Chaux-de-Fonds": { multiplier: 0.75, verified: "confirmed" },
    "La Chaux-du-Milieu": { multiplier: 0.75, verified: "confirmed" },
    "La Côte-aux-Fées": { multiplier: 0.75, verified: "confirmed" },
    "La Grande Béroche": { multiplier: 0.63, verified: "confirmed" },
    "La Sagne": { multiplier: 0.75, verified: "confirmed" },
    "La Tène": { multiplier: 0.68, fiscalCommune: "Laténa", verified: "confirmed" },
    Laténa: { multiplier: 0.68, verified: "confirmed" },
    "Le Cerneux-Péquignot": { multiplier: 0.72, verified: "confirmed" },
    "Le Landeron": { multiplier: 0.66, verified: "confirmed" },
    "Le Locle": { multiplier: 0.69, verified: "confirmed" },
    "Les Planchettes": { multiplier: 0.77, verified: "confirmed" },
    "Les Ponts-de-Martel": { multiplier: 0.75, verified: "confirmed" },
    "Les Verrières": { multiplier: 0.79, verified: "confirmed" },
    Lignières: { multiplier: 0.67, verified: "confirmed" },
    "Marin-Epagnier": { multiplier: 0.68, fiscalCommune: "Laténa", verified: "confirmed" },
    Milvignes: { multiplier: 0.63, verified: "confirmed" },
    Neuchâtel: { multiplier: 0.65, verified: "confirmed" },
    Peseux: { multiplier: 0.65, fiscalCommune: "Neuchâtel", verified: "confirmed" },
    Rochefort: { multiplier: 0.67, verified: "confirmed" },
    "Saint-Blaise": { multiplier: 0.68, fiscalCommune: "Laténa", verified: "confirmed" },
    "Val-de-Ruz": { multiplier: 0.66, verified: "confirmed" },
    "Val-de-Travers": { multiplier: 0.76, verified: "confirmed" },
  },
  JU: {
    Alle: { multiplier: 2.25, verified: "confirmed" },
    "Basse-Allaine": { multiplier: 2.35, verified: "confirmed" },
    "Basse-Vendline": { multiplier: 2.1, verified: "confirmed" },
    Bassecourt: { multiplier: 2.1, fiscalCommune: "Haute-Sorne", verified: "confirmed" },
    Boncourt: { multiplier: 1.55, verified: "confirmed" },
    Bourrignon: { multiplier: 2.25, verified: "confirmed" },
    Boécourt: { multiplier: 2.0, verified: "confirmed" },
    Bure: { multiplier: 2.25, verified: "confirmed" },
    Châtillon: { multiplier: 2.0, verified: "confirmed" },
    "Clos du Doubs": { multiplier: 2.15, verified: "confirmed" },
    Coeuve: { multiplier: 2.35, verified: "confirmed" },
    Cornol: { multiplier: 2.05, verified: "confirmed" },
    Courchapoix: { multiplier: 2.15, verified: "confirmed" },
    Courchavon: { multiplier: 1.9, verified: "confirmed" },
    Courgenay: { multiplier: 2.05, verified: "confirmed" },
    Courrendlin: { multiplier: 2.25, verified: "confirmed" },
    Courroux: { multiplier: 2.15, verified: "confirmed" },
    Courtedoux: { multiplier: 2.2, verified: "confirmed" },
    Courtételle: { multiplier: 1.65, verified: "confirmed" },
    "Damphreux-Lugnez": { multiplier: 2.15, verified: "confirmed" },
    Delémont: { multiplier: 1.9, verified: "confirmed" },
    Develier: { multiplier: 1.95, verified: "confirmed" },
    Ederswiler: { multiplier: 2.2, verified: "confirmed" },
    Fahy: { multiplier: 2.3, verified: "confirmed" },
    Fontenais: { multiplier: 2.35, verified: "confirmed" },
    Grandfontaine: { multiplier: 2.25, verified: "confirmed" },
    "Haute-Ajoie": { multiplier: 2.15, verified: "confirmed" },
    "Haute-Sorne": { multiplier: 2.1, verified: "confirmed" },
    "La Baroche": { multiplier: 2.15, verified: "confirmed" },
    Lajoux: { multiplier: 2.2, verified: "confirmed" },
    "Le Bémont": { multiplier: 1.95, verified: "confirmed" },
    "Le Genevez": { multiplier: 2.05, verified: "confirmed" },
    "Le Noirmont": { multiplier: 1.7, verified: "confirmed" },
    "Les Bois": { multiplier: 2.05, verified: "confirmed" },
    "Les Breuleux": { multiplier: 1.3, verified: "confirmed" },
    "Les Enfers": { multiplier: 2.05, verified: "confirmed" },
    Mervelier: { multiplier: 2.25, verified: "confirmed" },
    Mettembert: { multiplier: 2.2, verified: "confirmed" },
    Montfaucon: { multiplier: 2.2, verified: "confirmed" },
    Moutier: { multiplier: 2.3, verified: "confirmed" },
    Movelier: { multiplier: 2.25, verified: "confirmed" },
    Muriaux: { multiplier: 1.6, verified: "confirmed" },
    Pleigne: { multiplier: 2.1, verified: "confirmed" },
    Porrentruy: { multiplier: 2.05, verified: "confirmed" },
    Rossemaison: { multiplier: 2.0, verified: "confirmed" },
    Saignelégier: { multiplier: 2.3, verified: "confirmed" },
    Saulcy: { multiplier: 2.2, verified: "confirmed" },
    Soubey: { multiplier: 2.25, verified: "confirmed" },
    Soyhières: { multiplier: 2.15, verified: "confirmed" },
    "St-Brais": { multiplier: 2.25, verified: "confirmed" },
    "Val Terbi": { multiplier: 2.2, verified: "confirmed" },
    Vendlincourt: { multiplier: 2.3, verified: "confirmed" },
    Vicques: { multiplier: 2.2, fiscalCommune: "Val Terbi", verified: "confirmed" },
  },
};

/**
 * Multiplicateur communal réel pour une commune donnée, si connue.
 * undefined si canton/commune absent de la liste → l'appelant garde le
 * comportement existant (chef-lieu par défaut via communalMultiplierCapital).
 */
export function getCommunalMultiplier(
  canton: string | null | undefined,
  commune: string | null | undefined,
): number | undefined {
  if (!canton || !commune) return undefined;
  const entry = COMMUNAL_MULTIPLIERS[canton.toUpperCase()]?.[commune.trim()];
  return entry?.multiplier;
}

/**
 * VS uniquement : indexation communale réelle pour une commune donnée, si
 * connue. undefined pour tout autre canton, ou si la commune est absente de
 * la liste → l'appelant garde le comportement existant (taux lu directement
 * sur le revenu réel, sans dé-indexation).
 */
export function getVsIndexation(
  canton: string | null | undefined,
  commune: string | null | undefined,
): number | undefined {
  if (!canton || canton.toUpperCase() !== "VS" || !commune) return undefined;
  const entry = COMMUNAL_MULTIPLIERS.VS?.[commune.trim()];
  return entry?.vsIndexationPercent;
}
